// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzyxusxaegznrspqhytn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6eXh1c3hhZWd6bnJzcHFoeXRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNzE4OTYsImV4cCI6MjA2Nzc0Nzg5Nn0.b0g9h-CJzjiaVvQ_dNc_9FBgZDleEzlUc5j_eHtkt0g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});